version: '3'

services:
  py:
    container_name: py
    build: .
    env_file: ./db.env
    environment:
      - TZ=Asia/Tokyo
    entrypoint: ["cron", "-f"]
    networks:
      rss:
        ipv4_address: 192.168.200.11
    depends_on:
      - db
    links:
      - db

  db:
    container_name: mysql
    image: mysql:5.7
    env_file: ./db.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '13306:3306'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d
    networks:
      rss:
        ipv4_address: 192.168.200.12


networks:
  rss:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
          gateway: 192.168.200.1
